-- Create 'posts' table for the Blog feature
CREATE TABLE IF NOT EXISTS public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    content TEXT NOT NULL, -- Markdown content
    excerpt TEXT,
    author_id UUID REFERENCES auth.users(id),
    published BOOLEAN DEFAULT FALSE,
    published_at TIMESTAMP WITH TIME ZONE,
    cover_image TEXT
);

-- Enable RLS
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- Policies
-- Everyone can read published posts
CREATE POLICY "Public can read published posts" ON public.posts FOR SELECT USING (published = true);

-- Admins can do everything
-- Note: This requires the user to have an admin role in 'user_roles' table (handled in app logic or via custom claim if setup)
-- For simplicity in this starter kit, we might allow all authenticated users to read all posts (drafts included) if they are admins.
-- But standard policy:
CREATE POLICY "Admins can manage all posts" ON public.posts USING (
  EXISTS (
    SELECT 1 FROM public.user_roles 
    WHERE user_id = auth.uid() AND role IN ('admin', 'owner')
  )
);

-- Indexes
CREATE INDEX idx_posts_slug ON public.posts(slug);
CREATE INDEX idx_posts_published ON public.posts(published);
