-- Create tables for the Quiz and Results functionality

-- 1. Create 'questions' table
CREATE TABLE IF NOT EXISTS public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    subject TEXT NOT NULL,
    question_text TEXT NOT NULL,
    order_index INTEGER NOT NULL DEFAULT 0
);

-- 2. Create 'options' table
CREATE TABLE IF NOT EXISTS public.options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    question_id BIGINT REFERENCES public.questions(id) ON DELETE CASCADE,
    option_text TEXT NOT NULL,
    score_value INTEGER NOT NULL, -- Value from 1-5, or special code like 6 for custom
    is_custom BOOLEAN DEFAULT FALSE
);

-- 3. Create 'user_responses' table
CREATE TABLE IF NOT EXISTS public.user_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    question_id BIGINT REFERENCES public.questions(id) ON DELETE CASCADE,
    selected_option_id BIGINT REFERENCES public.options(id),
    custom_answer TEXT,
    score_value INTEGER -- Store the value for easier calculations
);

-- 4. Create 'career_paths' table (for future use in Results)
CREATE TABLE IF NOT EXISTS public.career_paths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    recommended_streams TEXT[]
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.career_paths ENABLE ROW LEVEL SECURITY;

-- Policies for 'questions' and 'options' (Readable by everyone, Writable by Admins only)
CREATE POLICY "Allow public read access to questions" ON public.questions FOR SELECT USING (true);
CREATE POLICY "Allow public read access to options" ON public.options FOR SELECT USING (true);

-- Policies for 'user_responses' (Users can read/write their own)
CREATE POLICY "Users can insert their own responses" ON public.user_responses FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can read their own responses" ON public.user_responses FOR SELECT USING (auth.uid() = user_id);

-- Seed initial data (based on the hardcoded questions in Quiz.tsx)
INSERT INTO public.questions (subject, question_text, order_index) VALUES
('Mathematics', 'How interested are you in solving complex mathematical problems?', 1),
('Science', 'How much do you enjoy conducting experiments and understanding scientific concepts?', 2),
('Literature', 'How passionate are you about reading, writing, and analyzing texts?', 3),
('History', 'How interested are you in learning about past events and their impact on society?', 4),
('Arts', 'How creative do you feel when expressing yourself through art, music, or design?', 5),
('Technology', 'How enthusiastic are you about working with computers and emerging technologies?', 6);

-- Seed options for the questions (Simplified loop for standard options)
-- We'll assume the IDs 1-6 for the inserted questions.
DO $$
DECLARE
    q_id INT;
    opt_text TEXT;
    score INT;
BEGIN
    FOR q_id IN 1..6 LOOP
        -- Standard Options 1-5
        INSERT INTO public.options (question_id, option_text, score_value) VALUES
        (q_id, 'Not interested', 1),
        (q_id, 'Slightly interested', 2),
        (q_id, 'Moderately interested', 3),
        (q_id, 'Very interested', 4),
        (q_id, 'Extremely interested', 5);
        
        -- Custom Option (Not applicable/Custom) logic omitted for brevity in seed, 
        -- but frontend handles it.
    END LOOP;
END $$;
