import { analyzeStudent, validateAnalysisInput } from "./index";
const base = { schema_version: "1.0" as const, student: { name: "Asha", grade: 12, stream: "Commerce" }, subjects: [{ name: "Accountancy", marks: 88, max_marks: 100 }, { name: "Mathematics", marks: 92, max_marks: 100 }, { name: "Economics", marks: 76, max_marks: 100 }], skills: { analytical: 88, communication: 82, logical: 85 }, interests: { finance: 90, business: 85, technology: 70 }, aptitude: { numerical: 82 } };
describe("Analysis Engine v1", () => {
  it("calculates weighted percentages, ranks subjects, and identifies areas", () => { const result = analyzeStudent(base); expect(result.academic_analysis?.overall_percentage).toBe(85.3); expect(result.subject_analysis.map(item => item.name)).toEqual(["Mathematics", "Accountancy", "Economics"]); expect(result.academic_analysis?.strengths).toEqual(["Mathematics", "Accountancy"]); });
  it("supports different maximum marks", () => { const result = analyzeStudent({ ...base, subjects: [{ name: "Math", marks: 45, max_marks: 50 }, { name: "English", marks: 180, max_marks: 200 }] }); expect(result.academic_analysis?.overall_percentage).toBe(90); });
  it("calculates trends only from supplied historic results", () => { const result = analyzeStudent({ ...base, previous_examinations: [{ subjects: [{ name: "Accountancy", marks: 70, max_marks: 100 }, { name: "Mathematics", marks: 78, max_marks: 100 }, { name: "Economics", marks: 72, max_marks: 100 }] }] }); expect(result.trend_analysis).toMatchObject({ trend_status: "available", overall_change: 12 }); expect(result.trend_analysis.subjects?.find(item => item.name === "Mathematics")?.change).toBe(14); });
  it("ranks configured career profiles deterministically", () => { const result = analyzeStudent(base); expect(result.career_matches[0]).toMatchObject({ career: "Chartered Accountant (CA)" }); expect(result.career_matches[0].positive_factors.length).toBeGreaterThan(0); });
  it("matches colleges only against supplied verified course data", () => { const result = analyzeStudent(base, { college_catalog: [{ id: "college-1", name: "Commerce College", location: "Mumbai", courses: ["B.Com Finance"], rating: 4.5 }] }); expect(result.college_recommendations).toHaveLength(1); expect(result.college_recommendations[0].matched_courses).toContain("B.Com Finance"); });
  it("returns structured validation errors for invalid, duplicate, and missing inputs", () => { expect(validateAnalysisInput(null)).toMatchObject({ valid: false }); expect(validateAnalysisInput({ ...base, subjects: [{ name: "Math", marks: 101, max_marks: 100 }] }).errors[0].path).toContain("marks"); expect(validateAnalysisInput({ ...base, subjects: [{ name: "Math", marks: 1, max_marks: 1 }, { name: "math", marks: 1, max_marks: 1 }] }).errors.some(error => error.message === "duplicate subject")).toBe(true); });
  it("handles boundary values and reports missing trend data", () => { const result = analyzeStudent({ ...base, subjects: [{ name: "Math", marks: 0, max_marks: 100 }] }); expect(result.academic_analysis?.performance_category).toBe("Needs Improvement"); expect(result.trend_analysis.trend_status).toBe("insufficient_data"); });
});
