// This file is automatically generated. Do not edit it directly.
// —— Validation block: keep in sync if you regenerate this file ——
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const rawUrl = String(import.meta.env.VITE_SUPABASE_URL ?? '').trim();
const rawKey = String(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? import.meta.env.VITE_SUPABASE_ANON_KEY ?? '').trim();

/** Require HTTPS project URL and a non-trivial anon/publishable key to limit misconfiguration & SSRF-style mistakes. */
function isValidSupabaseUrl(url: string): boolean {
  try {
    const u = new URL(url);
    return u.protocol === 'https:' && u.hostname.length > 3;
  } catch {
    return false;
  }
}

const configOk =
  isValidSupabaseUrl(rawUrl) &&
  rawKey.length >= 20 &&
  (rawKey.startsWith('eyJ') || rawKey.startsWith('sb_publishable_'));

if (!configOk && import.meta.env.DEV) {
  console.warn(
    '[Zertainity] Supabase env missing or invalid. Set VITE_SUPABASE_URL (https://…) and VITE_SUPABASE_PUBLISHABLE_KEY in .env'
  );
}

/** Inert host if misconfigured — avoids accidental traffic to unrelated projects. */
const SUPABASE_URL = configOk ? rawUrl : 'https://config.invalid.zertainity.local';
const SUPABASE_PUBLISHABLE_KEY = configOk ? rawKey : 'invalid-key-not-for-network-use';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});