// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Fallback for missing keys to prevent app crash on empty deploy
const isValidConfig = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY;

if (!isValidConfig) {
  console.error("Supabase keys are missing! Check your environment variables.");
}

export const supabase = isValidConfig
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  })
  : createClient<Database>('https://placeholder.supabase.co', 'placeholder-key');
// Return a placeholder client so imports don't fail, but operations will fail gracefully or via auth checks
